<a href="https://colab.research.google.com/github/SimonBIgnacio/primeros_codigos/blob/main/Intro_arrays_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
precio = [2,1,10]
cantidad_vendida = [17,40,1]
costo = [0.25, 0.50, 5]

import numpy as np
precio_array = np.array(precio)
cantidad_vendida_array = np.array(cantidad_vendida)
costo_array = np.array(costo)

ganancia_array = precio_array - costo_array
print(ganancia_array)

precio_array = np.append(precio_array,[7])
print(precio_array)

precio_array = np.append(precio_array,[4.5,3,4,9])
print(precio_array)

precio_array = np.delete(precio_array,-1)
print(precio_array)

precio_array[2] = 12
print(precio_array)

cantidad_vendida_array = np.append(cantidad_vendida_array,[2,3,16,5])
print(cantidad_vendida_array)

cantidad_vendida_array[1] = 39
print(cantidad_vendida_array)

pxq_array = cantidad_vendida_array * precio_array #aqui deje PxQ que es venta. quizas puedas puedes descontar los costos pero no tenemos los costos de los datos agregados
print(pxq_array)

merma = [0,0,2,1,6,0,2]
merma_array = np.array(merma)
print(merma_array)

pxq_merma_array = merma_array * precio_array/2
print(pxq_merma_array)

pxq_total_array = pxq_array + pxq_merma_array
print(pxq_total_array)

suma_total = np.sum(pxq_total_array)
print(suma_total)



[1.75 0.5  5.  ]
[ 2  1 10  7]
[ 2.   1.  10.   7.   4.5  3.   4.   9. ]
[ 2.   1.  10.   7.   4.5  3.   4. ]
[ 2.   1.  12.   7.   4.5  3.   4. ]
[17 40  1  2  3 16  5]
[17 39  1  2  3 16  5]
[34.  39.  12.  14.  13.5 48.  20. ]
[0 0 2 1 6 0 2]
[ 0.   0.  12.   3.5 13.5  0.   4. ]
[34.  39.  24.  17.5 27.  48.  24. ]
213.5
